### ISSUE TITLE
Troops Upgrade is ignoring the Disciplinarian perk rules

### ISSUE THREAD

**Issue by SerjTargarien** [tbeswick96/BannerlordYetAnotherPartyOrganiser#18] opened 2020-04-19 11:13 UTC
The "Upgrade all" button can upgrade bandits into normal troops without the disciplinarian perk. It should do a check before doing so and ignore those troops if you don't have it.

Additionally, this is not a bug report but a suggestion. When upgrade rules are finally implemented, "don't upgrade bandits" should be implemented as a rule for role-playing purposes.

**Comment by MLNW** [comment] 2020-04-19 11:14
Duplicate of #5, sounds like it wasn't fixed after all @tbeswick96

**Comment by MLNW** [comment] 2020-04-19 11:15
Closing in favor of old issue

**Closed as completed by MLNW** 2020-04-19 11:15 UTC
Labels: kind/bug, status/duplicate
