### ISSUE TITLE
After some time passes in a new save, the game begins to crash when i try to take prisoners

### ISSUE THREAD

**Issue by flauvious** [tbeswick96/BannerlordYetAnotherPartyOrganiser#23] opened 2020-04-20 08:12 UTC
Hi, I've started over several times now with this mod, at first everything works fine but after some time passes eventually trying to recruit prisoners crashes the game. And when that happens that save is basically ruined, as attempting to transfer prisoners to my party always crashes the game. I disabled every other mod I had expect this one and the ones this one requires and it still crashes. I start a new game, works fine for awhile, then taking prisoners crashes the game.

**Comment by MLNW** [comment] 2020-04-20 08:48
Which version of the mod were you using?

Could you provide us with a save game show casing the issue?

**Comment by tbeswick96** [comment] 2020-04-20 11:02
@flauvious Yeah if you could upload a save file and modlist here, we can find the cause of the issue better.
Sorry you're having problems!

**Comment by MLNW** [comment] 2020-04-24 17:36
Without a save game or other information about this issue we sadly cannot help. Closing for now.

**Closed as completed by MLNW** 2020-04-24 17:36 UTC
Labels: kind/bug, status/need more info
